### ISSUE TITLE
64bit以外のアクセス幅でのバーストのサポート

### ISSUE THREAD

**Issue by HidetaroTanaka** [NakajoLab/B4-Processor#108]
## What
8, 16, 32bit幅でのバーストのサポート

## How
`SimpleAXIMemoryWithSimulationIO.scala`でのreadAddrの計算が8Byteごとにインクリメントされているため，readならばここを修正するべき？

```scala
    when(!readState.empty) {
      when(readState.output.bits.address === memAddrMask) {
        readAddr := readState.output.bits
          .address(63, 3) + readBurstLen + (axi.read.ready && readDone).asUInt
```

## Problems
- 命令フェッチ時のバースト転送はどうなっているか
- 8, 16, 32bit幅のアクセス時の仕様の確認

**Comment by HidetaroTanaka** [comment]
https://github.com/NakajoLab/B4-Processor-V/tree/vectorBranch

例えばここのvecLoad.cだとv10ベクトルレジスタ(e32)に0,1,2,...と入ってほしいが，バーストが64bitごとなので0,2,4,...となる

**Comment by pineapplehunter** [comment]
AXI経由の通信は基本的に64bitにしたいと考えています．
これは転送にかかるクロック数を下げるためとインタフェースの簡易化のためです．
現在8,16,32bitのデータをロードする際には64bitで受け取り，内部で切り出して値として使用しています．ストアの場合は64bitのデータにマスクを掛けて保存しています．

64bit以外のバースト転送を実装するための主な変更箇所としては次があると思います．
- ExternalMemoryInterface（64bitバースト転送のみを考えていたため）
- シミュレーション用のメモリ（64bitのみを想定して実装したため）

もし64bitのデータから切り出す方法で問題がありそうでしたらできれば具体例とともに教えてほしいです．

**Comment by HidetaroTanaka** [comment]
了解しました
明日のミーティングで相談を持ち掛けようと思っていましたが、ベクトル側の仕様変更でとりあえず対応させようと思います

**Comment by pineapplehunter** [comment]
承知しました。
この機能が必要だという判断になればまた連絡お願いします！
